-- MySQL Script generated by MySQL Workbench
-- 11/19/14 21:03:55
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP database mydb;
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`people`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`people` ;

CREATE TABLE IF NOT EXISTS `mydb`.`people` (
  `id` INT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Customer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `id` INT NOT NULL,
  `cust_id` VARCHAR(45) UNIQUE NOT NULL,
  `cust_password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `cust_id`),
  CONSTRAINT `fk_id`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`people` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Employee` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `id` INT UNIQUE NOT NULL,
  `emp_id` VARCHAR(45) UNIQUE NOT NULL,
  `emp_password` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `emp_id`),
  CONSTRAINT `fk_emp_id`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`people` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Account` ;

CREATE TABLE Account (
  account_number INT UNIQUE NOT NULL,
  `balance` DECIMAL(8,2) NULL,
  cust_id VARCHAR(45) UNIQUE NOT NULL,
  `interest_rate` DECIMAL(4,2) NOT NULL,
  PRIMARY KEY (account_number),
  CONSTRAINT 
    FOREIGN KEY (cust_id)
    REFERENCES `mydb`.`customer` (cust_id)
	)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TransType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TransType` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TransType` (
  `trans_type_code` VARCHAR(20) UNIQUE NOT NULL,
  `decription` VARCHAR(45) NULL,
  PRIMARY KEY (`trans_type_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Transaction` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Transaction` (
  `trans_id` INT NOT NULL,
  `amount` DECIMAL(6,2) NOT NULL,
  `trans_type_code` VARCHAR(20) NOT NULL,
  `account_number` INT NOT NULL,
  `trans_date` TIMESTAMP NOT NULL,
  `cust_id` VARCHAR(45) UNIQUE NOT NULL,
  `emp_id` VARCHAR(45) UNIQUE NOT NULL,
  PRIMARY KEY (`trans_id`),
  CONSTRAINT `fk_account_number`
    FOREIGN KEY (`account_number`)
    REFERENCES `Account` (`account_number`),
  CONSTRAINT `fk_trans_type_code`
    FOREIGN KEY (`trans_type_code`)
    REFERENCES `mydb`.`TransType` (`trans_type_code`),
  CONSTRAINT `fk_trans_cust_id`
    FOREIGN KEY (`cust_id`)
    REFERENCES `mydb`.`Customer` (`cust_id`),
  CONSTRAINT `fk_trans_emp_id`
    FOREIGN KEY (`emp_id`)
    REFERENCES `mydb`.`Employee` (`emp_id`))
;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
