
-- -----------------------------------------------------
-- Data for table `mydb`.`people`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1001, 'Brielle', 'Fisher', 'Nunc@Fusce.edu');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1002, 'Malcolm', 'Contreras', 'diam@amifringilla.edu');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1003, 'Carolyn', 'Marsh', 'consectetuer.cursus@lectus.edu');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1004, 'Iliana', 'Byers', 'turpis@lectusNullam.org');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1005, 'Cherokee', 'Anthony', 'Nunc.lectus@Pellenciesdignissim.com');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1006, 'Macey', 'Rhodes', 'amet.orci@anuncIn.com');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1007, 'Colorado', 'Sherman', 'in@luctusaliquet.com');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1008, 'Brady', 'Trevino', 'sem@eget.co.uk');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1009, 'Ila', 'Adkins', 'egestas.a@necluctus.net');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1010, 'Joy', 'Oliver', 'nec.enim@gravidasagittis.org');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1011, 'Tashya', 'Steele', 'magna.Sed.eu@adipiscing.ca');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1012, 'Amethyst', 'Burris', 'velit.eget.laoreet@utaliquamiaculis.edu');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1013, 'Fulton', 'Whitfield', 'sem.elit@dolor.com');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1014, 'Ariana', 'Riggs', 'nonummy@euismodetcommodo.org');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1015, 'Chloe', 'Eaton', 'dictum.cursus.Nunc@famesac.com');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1016, 'Sydnee', 'Langley', 'quam@dolorDonec.org');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1017, 'Andrew', 'Ray', 'ametr.adipiscing@facilisismagna.com');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1018, 'Yasir', 'Drake', 'iaculis@inmolestietortor.net');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1019, 'Raymond', 'Grant', 'Sed@felis.ca');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1020, 'Reagan', 'Travis', 'ac@luctuset.org');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1021, 'Doris', 'Walls', 'et@ornareFuscemollis.org');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1022, 'Allen', 'Montgomery', 'habitant.morbi.tristique@mauriselit.edu');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1023, 'Carol', 'Mercado', 'Fusce.mollis@euplacerateget.edu');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1024, 'Macy', 'Gilliam', 'mollis.lectus@nullaCras.edu');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1025, 'Jesse', 'Barrett', 'arcu@Quisquenonummyipsum.net');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1026, 'Sonya', 'Hopper', 'sit@non.ca');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1027, 'Cyrus', 'Cabrera', 'risus@libero.net');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1028, 'Myles', 'Brock', 'ornare@eueuismod.edu');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1029, 'Nadine', 'Doyle', 'leo.Cras@ProinmiAliquam.edu');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1030, 'Arden', 'Sanchez', 'commodo.auctor.velit@dis.co.uk');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1031, 'Phillip', 'Barnett', 'ut.aliquam.iaculis@etarcuimperdiet.org');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1032, 'Wendy', 'Vincent', 'quis.diam@sem.org');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1033, 'Joelle', 'Welch', 'lectus.Nullam@pretiumaliquetmetus.ca');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1034, 'Gavin', 'Leach', 'fringilla@InloremDonec.ca');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1035, 'Paloma', 'Obrien', 'ac.fermentum@necdiamDuis.ca');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1036, 'Candice', 'Vincent', 'lorem.tristique.aliquet@Nullaeu.co.uk');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1037, 'Plato', 'Clay', 'lacinia@Pellentesqueultriciesdignissim.net');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1038, 'Lunea', 'Norman', 'orci.Donec@sempereratin.org');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1039, 'Dalton', 'Ingram', 'malesuada@fermentum.com');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1040, 'Jena', 'Fleming', 'sit.amet@vitaesodalesnisi.com');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1041, 'Upton', 'Bennett', 'lacus@antedictummi.org');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1042, 'Mollie', 'Buck', 'nisi.Cum.sociis@amet.co.uk');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1043, 'Beck', 'Martinez', 'tellus@bibendumfermentum.net');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1044, 'Ryder', 'Parsons', 'egestas@augue.ca');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1045, 'Jemima', 'Roth', 'Suspendisse.molestie@madisparturient.ca');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1046, 'Clarke', 'Kline', 'Quisque.porttitor@eget.net');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1047, 'Jena', 'Wilder', 'Quisque.imperd.erat@scelerisquelorem.co.uk');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1048, 'Valentine', 'Avery', 'Sed.id@aliquet.org');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1049, 'Sharon', 'Webb', 'Vivamus@etipsumcursus.net');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1050, 'Cheyenne', 'Lowery', 'dui.Suspene.ac@gravidamolestiearcu.edu');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1051, 'Elmo', 'Pearson', 'lorem.luctus@dapibusrutrum.edu');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1052, 'Zenaida', 'Roman', 'ac@tincidunt.edu');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1053, 'Wesley', 'Norton', 'tempus@utnullaCras.net');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1054, 'Joshua', 'Cooley', 'primis.in@cursuspurus.ca');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1055, 'Halee', 'Bartlett', 'orci.luctus.et@antebibendum.com');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1056, 'Darrel', 'Ruiz', 'neque@lectus.com');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1057, 'Dacey', 'Fitzgerald', 'in@amet.co.uk');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1058, 'Helen', 'Lowery', 'enim@Cras.com');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1059, 'Faith', 'Clarke', 'ut@DuisgravidaPraesent.co.uk');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1060, 'Ashton', 'Terry', 'commodo.at.libero@Ut.ca');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1061, 'Orla', 'Burch', 'velit.in.aliquet@sollicitudinorcisem.ca');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1062, 'Martin', 'Mullins', 'faucibus.leo@ultriciesornare.ca');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1063, 'Myles', 'Murphy', 'Curae@sitamet.co.uk');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1064, 'Sean', 'Collins', 'elit.elit.fermentum@lectus.ca');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1065, 'Helen', 'Kirkland', 'pede.Suspendisse.dui@Donectempor.org');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1066, 'Dakota', 'Cole', 'sit@nec.edu');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1067, 'Jaden', 'Luna', 'nec@accumsanneque.net');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1068, 'Jamalia', 'Gilmore', 'Nulla.eu@eleifendnon.ca');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1069, 'Daniel', 'Ewing', 'ut.odio@et.org');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1070, 'Emma', 'Kim', 'cursus@nonquamPellentesque.com');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1071, 'Alan', 'Graham', 'scelerisque.neque.sed@eget.edu');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1072, 'Cecilia', 'Lynch', 'mauris.Morbi.non@sedest.co.uk');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1073, 'Odessa', 'Newman', 'risus@Nullaegetmetus.edu');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1074, 'Quamar', 'Norris', 'lobortis.Class@volutpatNulla.edu');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1075, 'Anastasia', 'Quinn', 'pellentesque.massa.lobortis@quis.org');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1076, 'Vielka', 'Hatfield', 'mauris@musAeneaneget.edu');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1077, 'Emma', 'Guzman', 'nisl.arcu@fermentum.net');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1078, 'Kevyn', 'Travis', 'nec.luctus.felis@sociisnatoquepenatibus.co.uk');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1079, 'Reuben', 'Sweeney', 'fringilla@turpisvitae.com');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1080, 'Janna', 'Blankenship', 'eget@metus.org');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1081, 'Porter', 'Best', 'dis.parturient@orciDonecnibh.org');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1082, 'Chastity', 'Wilkins', 'eget.magna.Suspendisse@urnaUt.ca');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1083, 'Christen', 'Dominguez', 'augue.ac@interdumenimnon.net');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1084, 'Justine', 'Pierce', 'Proin.ultrices@duiFuscediam.com');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1085, 'Howard', 'Meyers', 'rutrum.Fusce.dolor@Sedegetlacus.net');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1086, 'Ocean', 'Woods', 'tempor@adlitora.co.uk');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1087, 'Kendall', 'Hardin', 'ac.libero.nec@pretiumnequeMorbi.ca');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1088, 'Omar', 'Shepherd', 'fringilla@adipiscinglacusUt.com');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1089, 'Nash', 'Gordon', 'leo@eratSednunc.com');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1090, 'Kathleen', 'Garrison', 'natoque.penatibus.et@sales.ca');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1091, 'Chaney', 'Stevenson', 'leo.Vivamus@euaugue.com');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1092, 'Gannon', 'Gordon', 'lacus@Morbi.co.uk');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1093, 'Juliet', 'House', 'ullamcorper@ac.org');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1094, 'Aquila', 'Holman', 'ornare@enimnectempus.co.uk');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1095, 'Thomas', 'Downs', 'non@egestasrhoncusProin.edu');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1096, 'Oleg', 'Cotton', 'arcu.eu@nibh.edu');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1097, 'John', 'Coleman', 'Donec@luctusvulputate.ca');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1098, 'Colby', 'Osborne', 'dis.parturient.montes@magnaa.com');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1099, 'Finn', 'Dillon', 'dictum.magna.Ut@Donecdignissim.edu');
INSERT INTO `mydb`.`people` (`id`, `first_name`, `last_name`, `email`) VALUES (1100, 'Kim', 'Lee', 'Donec.non.justo@Sednullaante.net');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Customer`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1001, 'C1001', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1002, 'C1002', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1003, 'C1003', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1004, 'C1004', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1005, 'C1005', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1006, 'C1006', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1007, 'C1007', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1008, 'C1008', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1009, 'C1009', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1010, 'C1010', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1011, 'C1011', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1012, 'C1012', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1013, 'C1013', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1014, 'C1014', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1015, 'C1015', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1016, 'C1016', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1017, 'C1017', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1018, 'C1018', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1019, 'C1019', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1020, 'C1020', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1021, 'C1021', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1022, 'C1022', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1023, 'C1023', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1024, 'C1024', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1025, 'C1025', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1026, 'C1026', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1027, 'C1027', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1028, 'C1028', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1029, 'C1029', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1030, 'C1030', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1031, 'C1031', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1032, 'C1032', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1033, 'C1033', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1034, 'C1034', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1035, 'C1035', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1036, 'C1036', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1037, 'C1037', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1038, 'C1038', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1039, 'C1039', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1040, 'C1040', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1041, 'C1041', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1042, 'C1042', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1043, 'C1043', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1044, 'C1044', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1045, 'C1045', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1046, 'C1046', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1047, 'C1047', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1048, 'C1048', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1049, 'C1049', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1050, 'C1050', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1051, 'C1051', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1052, 'C1052', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1053, 'C1053', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1054, 'C1054', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1055, 'C1055', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1056, 'C1056', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1057, 'C1057', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1058, 'C1058', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1059, 'C1059', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1060, 'C1060', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1061, 'C1061', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1062, 'C1062', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1063, 'C1063', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1064, 'C1064', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1065, 'C1065', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1066, 'C1066', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1067, 'C1067', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1068, 'C1068', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1069, 'C1069', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1070, 'C1070', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1071, 'C1071', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1072, 'C1072', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1073, 'C1073', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1074, 'C1074', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1075, 'C1075', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1076, 'C1076', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1077, 'C1077', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1078, 'C1078', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1079, 'C1079', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1080, 'C1080', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1081, 'C1081', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1082, 'C1082', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1083, 'C1083', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1084, 'C1084', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1085, 'C1085', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1086, 'C1086', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1087, 'C1087', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1088, 'C1088', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1089, 'C1089', 'DogCat');
INSERT INTO `mydb`.`Customer` (`id`, `cust_id`, `cust_password`) VALUES (1090, 'C1090', 'DogCat');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Employee`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Employee` (`id`, `emp_id`, `emp_password`, `role`) VALUES (1091, 'EMP1001', '123Rat', 'admin');
INSERT INTO `mydb`.`Employee` (`id`, `emp_id`, `emp_password`, `role`) VALUES (1092, 'EMP1002', '123Rat', 'admin');
INSERT INTO `mydb`.`Employee` (`id`, `emp_id`, `emp_password`, `role`) VALUES (1093, 'EMP1003', '123Frog', 'clerk');
INSERT INTO `mydb`.`Employee` (`id`, `emp_id`, `emp_password`, `role`) VALUES (1094, 'EMP1004', '123Frog', 'clerk');
INSERT INTO `mydb`.`Employee` (`id`, `emp_id`, `emp_password`, `role`) VALUES (1095, 'EMP1005', '123Frog', 'clerk');
INSERT INTO `mydb`.`Employee` (`id`, `emp_id`, `emp_password`, `role`) VALUES (1096, 'EMP1006', '123Frog', 'clerk');
INSERT INTO `mydb`.`Employee` (`id`, `emp_id`, `emp_password`, `role`) VALUES (1097, 'EMP1007', '123Frog', 'clerk');
INSERT INTO `mydb`.`Employee` (`id`, `emp_id`, `emp_password`, `role`) VALUES (1098, 'EMP1008', '123Frog', 'clerk');
INSERT INTO `mydb`.`Employee` (`id`, `emp_id`, `emp_password`, `role`) VALUES (1099, 'EMP1009', '123Frog', 'clerk');
INSERT INTO `mydb`.`Employee` (`id`, `emp_id`, `emp_password`, `role`) VALUES (1100, 'EMP1010', '123Rat', 'admin');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Account`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550001, 4116.46, 'C1001', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550002, 9572.91, 'C1002', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550003, 4960.91, 'C1003', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550004, 1380.92, 'C1004', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550005, 4738.44, 'C1005', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550006, 8535.07, 'C1006', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550007, 1569.40, 'C1007', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550008, 9734.17, 'C1008', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550009, 646.44, 'C1009', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550010, 4156.11, 'C1010', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550011, 10091.32, 'C1011', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550012, 274.08, 'C1012', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550013, 1893.07, 'C1013', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550014, 9095.91, 'C1014', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550015, 9211.81, 'C1015', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550016, 4788.37, 'C1016', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550017, 1408.12, 'C1017', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550018, 2103.41, 'C1018', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550019, 4542.47, 'C1019', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550020, 346.10, 'C1020', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550021, 1162.96, 'C1021', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550022, 7327.62, 'C1022', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550023, 3428.27, 'C1023', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550024, 8273.06, 'C1024', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550025, 10635.41, 'C1025', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550026, 5809.94, 'C1026', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550027, 7248.44, 'C1027', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550028, 1468.85, 'C1028', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550029, 5361.18, 'C1029', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550030, 6143.13, 'C1030', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550031, 3337.88, 'C1031', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550032, 5438.08, 'C1032', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550033, 4928.37, 'C1033', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550034, 2962.28, 'C1034', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550035, 8850.88, 'C1035', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550036, 7540.17, 'C1036', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550037, 7173.89, 'C1037', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550038, 2169.68, 'C1038', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550039, 1429.25, 'C1039', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550040, 9016.54, 'C1040', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550041, 3454.96, 'C1041', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550042, 8816.08, 'C1042', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550043, 727.89, 'C1043', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550044, 8928.14, 'C1044', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550045, 10051.24, 'C1045', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550046, 5441.15, 'C1046', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550047, 7228.67, 'C1047', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550048, 4606.97, 'C1048', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550049, 130.55, 'C1049', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550050, 8701.09, 'C1050', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550051, 10521.50, 'C1051', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550052, 7514.94, 'C1052', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550053, 4123.08, 'C1053', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550054, 8488.16, 'C1054', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550055, 10580.76, 'C1055', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550056, 10319.72, 'C1056', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550057, 8207.96, 'C1057', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550058, 3391.54, 'C1058', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550059, 8689.08, 'C1059', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550060, 8592.39, 'C1060', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550061, 1635.59, 'C1061', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550062, 5411.37, 'C1062', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550063, 1303.90, 'C1063', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550064, 5621.91, 'C1064', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550065, 9930.65, 'C1065', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550066, 9465.65, 'C1066', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550067, 7918.58, 'C1067', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550068, 8280.65, 'C1068', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550069, 7638.51, 'C1069', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550070, 2631.38, 'C1070', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550071, 7642.37, 'C1071', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550072, 5351.62, 'C1072', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550073, 6364.77, 'C1073', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550074, 8212.42, 'C1074', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550075, 880.83, 'C1075', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550076, 10404.55, 'C1076', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550077, 11048.95, 'C1077', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550078, 1210.90, 'C1078', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550079, 7677.49, 'C1079', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550080, 8803.63, 'C1080', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550081, 5762.83, 'C1081', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550082, 7558.96, 'C1082', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550083, 9623.82, 'C1083', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550084, 4011.95, 'C1084', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550085, 2428.89, 'C1085', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550086, 3101.98, 'C1086', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550087, 3112.66, 'C1087', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550088, 2006.59, 'C1088', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550089, 1952.00, 'C1089', 00.02);
INSERT INTO `mydb`.`Account` (`account_number`, `balance`, `cust_id`, `interest_rate`) VALUES (99550090, 7850.98, 'C1090', 00.02);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`TransType`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`TransType` (`trans_type_code`, `decription`) VALUES ('w', 'Withdrawal');
INSERT INTO `mydb`.`TransType` (`trans_type_code`, `decription`) VALUES ('d', 'Deposit');
INSERT INTO `mydb`.`TransType` (`trans_type_code`, `decription`) VALUES ('a', 'Adjustment');
INSERT INTO `mydb`.`TransType` (`trans_type_code`, `decription`) VALUES ('i', 'Interest');

COMMIT;

